### ISSUE TITLE
Property roles.

### ISSUE THREAD

**Issue by dantleech** [psiphp/content-type#4]
We should be able to assign roles to content-type properties, for example:

```yaml
properties:
    title:
        type: text
        role: title
    image:
        type: image
        role: primary_image
    ...
```

This will allow different types of content to be displayed in similar ways, for
example, in a list or browser.
